### ISSUE TITLE
Bom

### ISSUE THREAD

**Issue by tobyworks** [leonvandenbeukel/CNC-Machine-V3#1]
Seen the video, love it, maybe want to do one myself. Any chance you will create a bom with all the parts?

**Comment by bigbass1997** [comment]
I was wondering the same thing. Would really appreciate  BOM for this.

I asked on Twitter but haven't gotten a reply yet.

**Comment by leonvandenbeukel** [comment]
Not really a BOM but it might help you, I've added a cost estimation with parts I've used here: https://docs.google.com/spreadsheets/d/1WaLTZEe9Un130kNA_mwn08Lo0E_RAs8ju6dJp0eKexQ/edit?usp=sharing
