### ISSUE TITLE
Question: Which screws sizes and lengths are needed!

### ISSUE THREAD

**Issue by Multi94** [leonvandenbeukel/CNC-Machine-V3#2]
Hi,
I have a question about the cnc but in advance the router I like very well and I have decided to convert my Mpcnc to a router of its type. Unfortunately, I do not know what screws I need for it I would not necessarily buy half the hardware store to find the right screws. Could you maybe say something more specific so I can buy these screws then.

Thanks for your efforts.

**Comment by bigbass1997** [comment]
@Multi94 You can open the STL files into a CAD editor, such as Fusion 360, and use the inspect tool to check the sizes of each hole. From my peek at some of the files, it seems it uses primarily M6 (6mm) and M8 (8mm) sized holes.
