### ISSUE TITLE
Add 4th axis  to the CNC

### ISSUE THREAD

**Issue by nunoadferreira** [leonvandenbeukel/CNC-Machine-V3#4]
Hi,

You performed a great job by building this CNC. I really loved it. Congrats on that.

An idea I had while seeing your video is why don't add a 4th axis to the CNC and allow build relly complex objects.
I'm sure that many people (including myself) would patron that development.

Best regards

**Comment by leonvandenbeukel** [comment]
Thanks and I thought of that too. I might do that in the future.
